-- ============================================================
-- EXAM SECOURISTE — Schema
-- ============================================================

drop table if exists exam_secouriste_results;
drop table if exists exam_secouriste_sessions;

create table exam_secouriste_sessions (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  created_by text not null default '',
  themes jsonb not null default '[]',
  nb_questions int not null default 15,
  timer_sec int not null default 300,
  code text not null unique,
  actif boolean default true
);

alter table exam_secouriste_sessions enable row level security;
create policy "ins_session" on exam_secouriste_sessions for insert to anon with check (true);
create policy "sel_session" on exam_secouriste_sessions for select to anon using (true);
create policy "upd_session" on exam_secouriste_sessions for update to anon using (true) with check (true);
create policy "del_session" on exam_secouriste_sessions for delete to anon using (true);

create table exam_secouriste_results (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  session_id bigint references exam_secouriste_sessions(id),
  session_code text not null default '',
  name text not null,
  score int,
  correct int,
  total int,
  time_left int,
  finished boolean default false,
  eliminated boolean default false,
  answers jsonb,
  statut text default 'attente'
);

alter table exam_secouriste_results enable row level security;
create policy "ins_result" on exam_secouriste_results for insert to anon with check (true);
create policy "sel_result" on exam_secouriste_results for select to anon using (true);
create policy "upd_result" on exam_secouriste_results for update to anon using (true) with check (true);
